name: Docker-Image

on:
  workflow_dispatch:
  # enables manual trigger
  release:
    types: [ published ]

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        # ${{ github.repository_owner }} = FoodAppGroup --> must be lower case
        run: docker build . --file Dockerfile --tag ghcr.io/foodappgroup/freshplanner-ui:latest

      - name: Log in to Package Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push the Docker Image
        # ${{ github.repository_owner }} = FoodAppGroup --> must be lower case
        run: docker push ghcr.io/foodappgroup/freshplanner-ui:latest
